

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-filestore
spec:
  capacity:
    storage: 1Ti
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  nfs:
    path: /moodleshare
    server: 10.12.0.2 # filestore's internal IP