
---
apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: moodle
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80": "ingress-backendconfig", "443": "ingress-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: moodle
    app.kubernetes.io/name: moodle
  type: ClusterIP