
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-deployment
  namespace: moodle
spec:
  replicas: 3
  #strategy:
   # type: RollingUpdate
   # rollingUpdate:
    #  maxUnavailable: 1  # Pastikan hanya 1 pod yang ada saat restart
     # maxSurge: 0 
  selector:
    matchLabels:
      app.kubernetes.io/instance: moodle
      app.kubernetes.io/name: moodle
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: moodle
        app.kubernetes.io/name: moodle
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        # cloud.google.com/compute-class: "Balanced"
        # supported-cpu-platform.cloud.google.com/Intel_Ice_Lake: "true"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: moodle
                  app.kubernetes.io/name: moodle
              namespaces:
              - moodle
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - name: moodle
        image: asia-southeast1-docker.pkg.dev/vertical-jetty-448611-h5/moodle-filestore/moodle-nginx:ee180547-80ae-427b-b93a-25f173df6174 # make sure to differ moodle-nginx from moodle-bitnami
        imagePullPolicy: IfNotPresent
        ports:
        - name: moodle-port
          containerPort: 8080
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: moodle-externaldb
              key: mysql-password
        - name: MOODLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moodle-admin-password
              key: moodle-password
        - name: MOODLE_URL
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_URL
        - name: MOOSH_URL
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOOSH_URL
        - name: LANG
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: LANG
        - name: LANGUAGE
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: LANGUAGE
        - name: MOODLE_LANGUAGE
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_LANGUAGE
        - name: SITE_URL
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SITE_URL
        - name: MOODLE_DATAROOT_PATH
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_DATAROOT_PATH
        - name: MOODLE_PATH
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_PATH
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_TYPE
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_HOST
        - name: DB_HOST_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_HOST_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_USER
        - name: DB_PREFIX
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_PREFIX
        - name: MOODLE_SITENAME
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_SITENAME
        - name: MOODLE_SITESUMMARY
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_SITESUMMARY
        - name: MOODLE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_USERNAME
        - name: MOODLE_EMAIL
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_EMAIL
        - name: DB_READ_REPLICA_HOST
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_READ_REPLICA_HOST
        - name: DB_READ_REPLICA_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_READ_REPLICA_PORT
        - name: DB_READ_REPLICA_USER
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_READ_REPLICA_USER
        - name: DB_READ_REPLICA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: DB_READ_REPLICA_PASSWORD
        - name: REDIS_SESSION_ID_HOST
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_SESSION_ID_HOST
        - name: REDIS_SESSION_ID_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_SESSION_ID_PORT
        - name: REDIS_SESSION_ID_AUTH_STRING
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_SESSION_ID_AUTH_STRING
        - name: REDIS_APP_IP_AND_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_APP_IP_AND_PORT
        - name: REDIS_APP_AUTH_STRING
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_APP_AUTH_STRING
        - name: REDIS_SESSION_IP_AND_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_SESSION_IP_AND_PORT
        - name: REDIS_SESSION_AUTH_STRING
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_SESSION_AUTH_STRING
        - name: REDIS_LOCK_HOST_AND_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_LOCK_HOST_AND_PORT
        - name: REDIS_LOCK_AUTH_STRING
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: REDIS_LOCK_AUTH_STRING
        - name: SSLPROXY
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SSLPROXY
        - name: NOEMAIL_EVER
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: NOEMAIL_EVER
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SMTP_PORT
        - name: SMTP_USER
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SMTP_USER
        - name: SMTP_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SMTP_PASSWORD
        - name: SMTP_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: SMTP_PROTOCOL
        - name: MOODLE_MAIL_NOREPLY_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_MAIL_NOREPLY_ADDRESS
        - name: MOODLE_MAIL_PREFIX
          valueFrom:
            configMapKeyRef:
              name: moodle-configmap
              key: MOODLE_MAIL_PREFIX
          #livenessProbe:
           #failureThreshold: 60
           #httpGet:
             #path: /login/index.php
             #port: 8080
           #initialDelaySeconds: 600
           #periodSeconds: 10
           #successThreshold: 1
           #timeoutSeconds: 5
        # readinessProbe:
        #   failureThreshold: 6
        #   httpGet:
        #     path: /login/index.php
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
        #   successThreshold: 1
        #   timeoutSeconds: 3
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
        volumeMounts:
        - name: moodleroot-vol
          mountPath: /moodleroot-instance1/moodle
          subPath: moodleroot-instance1/moodle
        - name: moodleroot-vol
          mountPath: /moodleroot_instance1/moodledata
          subPath: moodleroot_instance1/moodledata
        - name: moodleroot-vol
          mountPath: /etc/nginx
          subPath: moodleroot_instance1/etc/nginx
        - name: moodleroot-vol
          mountPath: /etc/php81
          subPath: moodleroot_instance1/etc/php81
        - name: tmp-vol
          mountPath: /tmp
      volumes:
      - name: moodleroot-vol
        persistentVolumeClaim:
          claimName: pvc-filestore
      - name: tmp-vol
        emptyDir:
          medium: Memory
